ManagementSystem/ManagementSystem/urls.py
import debug_toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

from ManagementSystem import settings

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('ToDoDashboard.urls')),
    re_path(r'^__debug__', include(debug_toolbar.urls))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ManagementSystem/ToDoDashboard/urls.py
from django.contrib import admin
from django.urls import path

from ToDoDashboard.views import index

urlpatterns = [
    path('', index)
]

ManagementSystem/ToDoDashboard/models.py
from django.core.exceptions import ValidationError
from django.db import models

from ManagementSystem.settings import AUTH_USER_MODEL


class Member(models.Model):
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    avatar = models.ImageField(upload_to='photos/', blank=True)

    department = models.TextField(null=True, blank=True)


class Dashboard(models.Model):
    title = models.CharField(max_length=128)
    owner = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='member')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='LAST UPDATE')

    is_public = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.title}'


class DashboardColumn(models.Model):
    class Meta:
        verbose_name = 'Column'
        verbose_name_plural = 'Columns'

    dashboard = models.ForeignKey(Dashboard, on_delete=models.CASCADE, null=True)

    title = models.CharField(max_length=128)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}'


class ToDoItem(models.Model):
    """
    Represents a task assigned to a :model:`ToDoDashboard.Member`.
    Each task is attached to a :model:`ToDoDashboard.DashboardColumn`.
    """
    class Meta:
        verbose_name = 'ToDo Item'
        verbose_name_plural = 'ToDo Items'

    def clean(self):
        """
        Verifies that start_date goes behind due_date.
        :return: Raises ValidationError in case of a verification failure.
        """
        if self.start_date and self.due_date:
            if self.start_date > self.due_date:
                raise ValidationError('Dates are incorrect')

    dashboard_column = models.ForeignKey(DashboardColumn, on_delete=models.CASCADE)

    description = models.TextField()
    label = models.CharField(max_length=128, blank=True)

    start_date = models.DateTimeField(null=True, blank=True)
    due_date = models.DateTimeField(null=True, blank=True)

    time_estimate_hours = models.PositiveIntegerField(null=True, blank=True)
    comment = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    subtask_id = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'ToDo {self.id}'

ManagementSystem/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

ManagementSystem/ToDoDashboard/forms.py
from django import forms

from ToDoDashboard.models import ToDoItem


class ToDoItemForm(forms.ModelForm):
    class Meta:
        fields = ['description', 'label', 'comment', 'dashboard_column', 'start_date', 'due_date',
                  'time_estimate_hours']
        model = ToDoItem

    def clean(self):
        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('due_date')
        estimated_hours = self.cleaned_data.get('time_estimate_hours')

        if start_date and end_date:
            if start_date > end_date:
                raise forms.ValidationError('Dates are incorrect:'
                                            'due_date goes behind start_date')

        from datetime import timedelta
        if start_date + timedelta(hours=estimated_hours) > end_date:
            raise forms.ValidationError('Inconsistent dates and estimation. '
                                        'start_date+estimated_hours goes after '
                                        'due_date')

        return self.cleaned_data

ManagementSystem/ToDoDashboard/views.py
from django.contrib import admin
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, DetailView, UpdateView

from ToDoDashboard.forms import ToDoItemForm
from ToDoDashboard.models import Dashboard, ToDoItem


def index(request):
    print(request)
    return HttpResponse('<h1>Hello World!</h1>')


class DashboardListView(ListView):
    """
    Displays a list of available Dashboards.

    **Context**
    Dashboards are represented by the :model:`ToDoDashboard.Dashboard`

    ``ordering``
        Defines the ordering of Dashboards.

    **Template:**

    :template:`ToDoDashboard/kanban.html`
    """

    model = Dashboard
    template_name = 'kanban.html'
    ordering = 'title'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = 'Kanban'
        context['has_permission'] = True
        return context


class DashboardDetailView(DetailView, admin.ModelAdmin):
    """
    Displays ToDo items by columns.

    **Context**
    ToDo Items are represented by the :model:`ToDoDashboard.ToDoItem`
    Columns are represented by the :model:`ToDoDashboard.DashboardColumn`

    ``get_context_data``
        Setting title, has_permission and task_form.

    **Template:**

    :template:`ToDoDashboard/dashboard.html`
    """
    model = Dashboard
    template_name = 'dashboard.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.object.title
        context['has_permission'] = True
        context['task_form'] = ToDoItemForm()
        return context


class AjaxableResponseMixin:

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = serializers.serialize('json', [self.object])
            return JsonResponse(data, safe=False)
        else:
            return response


class TodoItemUpdate(AjaxableResponseMixin, UpdateView):
    model = ToDoItem
    fields = ['dashboard_column']
    success_url = '/'

ManagementSystem/users/views.py
from django.shortcuts import render

# Create your views here.

ManagementSystem/ToDoDashboard/templates/dashboard.html
{% extends 'admin/base_site.html' %}

{% load static reversing %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'css/dashboard.min.css' %}">
{% endblock %}

{% block content %}
    <div class="dashboard__add-column submit-row">
        <a href="{% admin_reverse 'dashboardcolumn' 'add' dashboard=object.pk %}" class="addlink">Add new column</a>
    </div>
    <div class="dashboard">
        <div class="dashboard__wrapper">
            {% for column in object.dashboardcolumn_set.all %}
                <div class="dashboard__column">
                    <div class="dashboard__column-wrapper">
                        <div class="dashboard__column-title">{{ column.title }}<a href="{% admin_reverse 'dashboardcolumn' 'change' column.pk dashboard=object.pk %}" class="changelink">Change</a><a href="{% admin_reverse 'dashboardcolumn' 'delete' column.pk dashboard=object.pk %}" class="deletelink">Delete</a></div>
                        <div class="dashboard__task-area" id="column-{{ column.pk }}">
                            {% for todo_item in column.todoitem_set.all %}
                                <div class="dashboard__task-item"id="drag-{{ todo_item.pk }}">
                                    <form action="" method="post" id="todo-{{ todo_item.pk }}" class="task-form">
                                        <div class="dashboard__task-title">{{ todo_item.label }}</div>
                                        <div class="dashboard__task-description">{{ todo_item.description|safe }}</div>
                                        <div class="form-data" style="display: none;">
                                            {% csrf_token %}
                                            <input type="hidden" name="dashboard_column">
                                        </div>
                                    </form>

                                    <a href="{% admin_reverse 'todoitem' 'change' todo_item.pk dashboard_column=column.pk %}" class="changelink">Change</a>
                                    <a href="{% admin_reverse 'todoitem' 'delete' todo_item.pk dashboard_column=column.pk %}" class="deletelink">Delete</a>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="dashboard__footer">
                            <a href="{% admin_reverse 'todoitem' 'add' dashboard_column=column.pk %}" class="default">Add new task</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    <script src="{% static 'js/drag-n-drop.min.js' %}"></script>
{% endblock %}

ManagementSystem/ToDoDashboard/templates/kanban.html
{% extends 'admin/base_site.html' %}

{% block content %}
    <ul>
        {% for object in object_list %}
            <li><a href="{% url 'admin:dashboard' object.pk %}">{{ object.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}